-- supabase/migrations/20260222_create_my_test_table.sql

CREATE TABLE public.my_test_table (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL
);

ALTER TABLE public.my_test_table ENABLE ROW LEVEL SECURITY;