
CREATE SCHEMA IF NOT EXISTS gtfs;


CREATE SCHEMA IF NOT EXISTS position_updates;
GRANT USAGE ON SCHEMA position_updates TO anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA position_updates 
GRANT ALL ON TABLES TO anon;

CREATE SCHEMA IF NOT EXISTS trip_updates;


-- CREATE SCHEMA IF NOT EXISTS alerts;
